'use client';

import React from 'react';
import { useTranslation } from '../../lib/i18n/LanguageContext';
import { ShieldCheck, EyeOff, Search, HelpCircle, Lock } from 'lucide-react';

export default function TrustPage() {
  const { dictionary } = useTranslation();

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-16 animate-fade-in">
      
      {/* Header */}
      <div className="text-center space-y-4 max-w-2xl mx-auto">
        <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-foreground font-sans">
          {dictionary.trust.title}
        </h1>
        <p className="text-muted text-base sm:text-lg">
          {dictionary.trust.subtitle}
        </p>
      </div>

      {/* Grid structure details */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Row 1, Col 1: t-1 principle */}
        <div className="bg-white border border-border-color rounded-2xl p-8 space-y-3">
          <div className="w-10 h-10 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent">
            <ShieldCheck className="w-5 h-5" />
          </div>
          <h3 className="text-lg font-bold text-foreground">
            {dictionary.trust.principleTitle}
          </h3>
          <p className="text-xs text-muted leading-relaxed">
            {dictionary.trust.principleDesc} We proactively address common pitfalls before users lose enrollment options.
          </p>
        </div>

        {/* Row 1, Col 2: Data minimization */}
        <div className="bg-white border border-border-color rounded-2xl p-8 space-y-3">
          <div className="w-10 h-10 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent">
            <EyeOff className="w-5 h-5" />
          </div>
          <h3 className="text-lg font-bold text-foreground">
            {dictionary.trust.dataTitle}
          </h3>
          <p className="text-xs text-muted leading-relaxed">
            {dictionary.trust.dataDesc} We only request coarse bands (e.g. Low/Mid/High income) in-session. We do not store medical records or Social Security numbers.
          </p>
        </div>

        {/* Row 2, Col 1: Full traceability */}
        <div className="bg-white border border-border-color rounded-2xl p-8 space-y-3">
          <div className="w-10 h-10 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent">
            <Search className="w-5 h-5" />
          </div>
          <h3 className="text-lg font-bold text-foreground">
            {dictionary.trust.traceTitle}
          </h3>
          <p className="text-xs text-muted leading-relaxed">
            {dictionary.trust.traceDesc} Every window calculation, cost score, and risk highlight is backed by verifiable regulatory reference lines.
          </p>
        </div>

        {/* Row 2, Col 2: No autonomous adverse decisions */}
        <div className="bg-white border border-border-color rounded-2xl p-8 space-y-3">
          <div className="w-10 h-10 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent">
            <Lock className="w-5 h-5" />
          </div>
          <h3 className="text-lg font-bold text-foreground">
            {dictionary.trust.humanTitle}
          </h3>
          <p className="text-xs text-muted leading-relaxed">
            {dictionary.trust.humanDesc} All system results are informational. Only humans hold authority to finalize coverages, issue formal plan approvals, or process claims.
          </p>
        </div>
      </div>

      {/* Compliance statement callout */}
      <div className="p-8 bg-slate-900 text-white rounded-3xl border border-slate-800 space-y-4">
        <h3 className="text-lg font-bold">Health Insurance Guidance Notice</h3>
        <p className="text-xs text-slate-400 leading-relaxed">
          askNewton is an informational guidance and education service. We are not a licensed insurance producer or broker, and we do not sell or bind insurance. 
        </p>
        <p className="text-xs text-slate-400 leading-relaxed">
          All recommendations are generated by a deterministic rules-based engine for educational purposes. For licensed advice and enrollment, consult a licensed insurance professional or coveredca.gov.
        </p>
      </div>

    </div>
  );
}
